# Generated by Django 4.0.6 on 2022-08-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=50)),
                ('bookname', models.CharField(max_length=50)),
                ('issuedate', models.DateField()),
                ('returndate', models.DateField()),
                ('charge', models.IntegerField()),
                ('is_deleted', models.CharField(max_length=10)),
            ],
        ),
    ]
