# Generated by Django 4.0.6 on 2022-08-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0002_book_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='uid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
